{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ja0tracker",
    "module": "ja0tracker-android",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.1.aar",
          "url": "ja0tracker-android-1.0.1.aar",
          "size": 200709,
          "sha512": "9048f6f0f94d78f739ae9d5430a2e10a85197216e9c6f125df9fcbcc746bb504833d007e733afddecb0542c8783b8ccc65bec7038e2a1dd867e6d132fee5e233",
          "sha256": "0636fd45fe2059f1c6ef026af18d3e26afb8b0fdedbf99e800244dab11223624",
          "sha1": "fe1d58ad80086dad0c2a5a4fbabb1400e4aa8bb3",
          "md5": "9d54af57069dd39086e5a7765b730421"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review-ktx",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.1.aar",
          "url": "ja0tracker-android-1.0.1.aar",
          "size": 200709,
          "sha512": "9048f6f0f94d78f739ae9d5430a2e10a85197216e9c6f125df9fcbcc746bb504833d007e733afddecb0542c8783b8ccc65bec7038e2a1dd867e6d132fee5e233",
          "sha256": "0636fd45fe2059f1c6ef026af18d3e26afb8b0fdedbf99e800244dab11223624",
          "sha1": "fe1d58ad80086dad0c2a5a4fbabb1400e4aa8bb3",
          "md5": "9d54af57069dd39086e5a7765b730421"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ja0tracker-android-1.0.1-sources.jar",
          "url": "ja0tracker-android-1.0.1-sources.jar",
          "size": 48903,
          "sha512": "c1893cd5ff4bc1105f9ac6d5d522afa6649fa6fffd94d56ef39a22ab95b95a6a50f4e529feca5a60922021753fb0eabe3601c12e23b642e7e77547cae7a1c732",
          "sha256": "7d74a640f449b932a28e001842d16108af32e4696530216198c61c964fa33e60",
          "sha1": "fbb73f9ebe3148716c8225c19346f8834b4bea96",
          "md5": "18455a68868076827abea41c2245c335"
        }
      ]
    }
  ]
}
