{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ja0tracker",
    "module": "ja0tracker-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.0.aar",
          "url": "ja0tracker-android-1.0.0.aar",
          "size": 200706,
          "sha512": "84dde66585b6de86ee24f719c420b7b9ac7065e6976f8ba77ca1dd77b160b51edbe22b31b83b0d6de685a5543924e3f93c30fd31885ee5d9d6ac11f0b6d13546",
          "sha256": "cb75f8627ec03d985c2efd43f956a07215cc96098fb143c697cfac5c24ebad96",
          "sha1": "5352817bf6e109bc50e9f7848369b4c2d2104962",
          "md5": "3a66535413a875566e3c02233fb1921b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review-ktx",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.0.aar",
          "url": "ja0tracker-android-1.0.0.aar",
          "size": 200706,
          "sha512": "84dde66585b6de86ee24f719c420b7b9ac7065e6976f8ba77ca1dd77b160b51edbe22b31b83b0d6de685a5543924e3f93c30fd31885ee5d9d6ac11f0b6d13546",
          "sha256": "cb75f8627ec03d985c2efd43f956a07215cc96098fb143c697cfac5c24ebad96",
          "sha1": "5352817bf6e109bc50e9f7848369b4c2d2104962",
          "md5": "3a66535413a875566e3c02233fb1921b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ja0tracker-android-1.0.0-sources.jar",
          "url": "ja0tracker-android-1.0.0-sources.jar",
          "size": 48903,
          "sha512": "c6ebcc9321dab5fbec3bf6c6b961f033268e420e59e2904b7e0442bb96535ade38a7a251799b37efb9ad8034b564118ea51b3439c6e867f34c4634c98bd7d9fd",
          "sha256": "b0ae00aeda5266162da903253560d7ff44ccc66c362e440097a5decb7b671296",
          "sha1": "040ee28c659583087ff6094b81110322da05edbd",
          "md5": "c9d4c774ad84bf5e1f26e5cd9d5f54d9"
        }
      ]
    }
  ]
}
