{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ja0tracker",
    "module": "ja0tracker-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.0.aar",
          "url": "ja0tracker-android-1.0.0.aar",
          "size": 200400,
          "sha512": "fab6fd5ead049bc6a00043890889cb53e1dcb8d269e63a29d91d625adc5d1046668ea8171eaeadd3b25745f5606020e8913a52f971ab753d40de9ee1c584ccc8",
          "sha256": "300319e98edfca81989841bec2130f78a363a5bcbc972da8c63f7e3f5c4ad78b",
          "sha1": "a7b6d1a0628ee873b8fa6f02e0592a8bf03e88a4",
          "md5": "d2bfb4bfe5648a9f9f154dcc680ad634"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review-ktx",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.0.aar",
          "url": "ja0tracker-android-1.0.0.aar",
          "size": 200400,
          "sha512": "fab6fd5ead049bc6a00043890889cb53e1dcb8d269e63a29d91d625adc5d1046668ea8171eaeadd3b25745f5606020e8913a52f971ab753d40de9ee1c584ccc8",
          "sha256": "300319e98edfca81989841bec2130f78a363a5bcbc972da8c63f7e3f5c4ad78b",
          "sha1": "a7b6d1a0628ee873b8fa6f02e0592a8bf03e88a4",
          "md5": "d2bfb4bfe5648a9f9f154dcc680ad634"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ja0tracker-android-1.0.0-sources.jar",
          "url": "ja0tracker-android-1.0.0-sources.jar",
          "size": 48813,
          "sha512": "5f6795b9990cd8bc0f7a57d8e35b05ce05e02d22d9967215b168e108eda1b353d23f553c30ddc18a97933362d49f6ac91639903b83098e0be3847fa0ca9a4c93",
          "sha256": "e174cb6288596d266d69c8d70a2ef8d5d7e39cd13d347fc68cb4788b57e05049",
          "sha1": "ae0fb3d63183a0924154730096ced656e4e5a772",
          "md5": "7051fd97685aae16db422b83390364d0"
        }
      ]
    }
  ]
}
