{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ja0tracker",
    "module": "ja0tracker-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.0.aar",
          "url": "ja0tracker-android-1.0.0.aar",
          "size": 200270,
          "sha512": "2f3bdcffa7a2bef26022144b10d3cc646f8335dd401e26adf1827dcb0a7690408dbede979a149274dc443df3413b51597555285aac432f36bc92946cca82bcf5",
          "sha256": "d950b2f9c8d117363e37a98c2150b22ad4b6cb76a7dca1d13203f6b0f7ba36a6",
          "sha1": "c2cc11453fc3c184ca55a30b0941898e03529939",
          "md5": "ad6de4f2a26b739d724ed3c7896dc78c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "review-ktx",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ja0tracker-android-1.0.0.aar",
          "url": "ja0tracker-android-1.0.0.aar",
          "size": 200270,
          "sha512": "2f3bdcffa7a2bef26022144b10d3cc646f8335dd401e26adf1827dcb0a7690408dbede979a149274dc443df3413b51597555285aac432f36bc92946cca82bcf5",
          "sha256": "d950b2f9c8d117363e37a98c2150b22ad4b6cb76a7dca1d13203f6b0f7ba36a6",
          "sha1": "c2cc11453fc3c184ca55a30b0941898e03529939",
          "md5": "ad6de4f2a26b739d724ed3c7896dc78c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ja0tracker-android-1.0.0-sources.jar",
          "url": "ja0tracker-android-1.0.0-sources.jar",
          "size": 48608,
          "sha512": "57e1d447de0a0ab480d224722c7100f369307e15688bb6fe13484853aac9316e97fd9abbcf21b1c7aa5be8d54cda2416ff75478717b633a1e802f196e279391d",
          "sha256": "4420b4d7ef7a6e72b9ef9444b8def0029045a30aaa77484155f45caba4c61f9e",
          "sha1": "fb2f36d84170024e8827fe09214dfce9f3770044",
          "md5": "724d928a4ce54c3b37d4c575baf5b41b"
        }
      ]
    }
  ]
}
