// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class ConfigMessage {
  ConfigMessage({
    required this.sdkKey,
    this.sdkSecret,
    this.appId,
    this.logLevel,
    this.waitForConsent,
    this.ingestBaseUrl,
    this.clickdBaseUrl,
  });

  String sdkKey;

  String? sdkSecret;

  String? appId;

  String? logLevel;

  bool? waitForConsent;

  String? ingestBaseUrl;

  String? clickdBaseUrl;

  Object encode() {
    return <Object?>[
      sdkKey,
      sdkSecret,
      appId,
      logLevel,
      waitForConsent,
      ingestBaseUrl,
      clickdBaseUrl,
    ];
  }

  static ConfigMessage decode(Object result) {
    result as List<Object?>;
    return ConfigMessage(
      sdkKey: result[0]! as String,
      sdkSecret: result[1] as String?,
      appId: result[2] as String?,
      logLevel: result[3] as String?,
      waitForConsent: result[4] as bool?,
      ingestBaseUrl: result[5] as String?,
      clickdBaseUrl: result[6] as String?,
    );
  }
}

class ConsentMessage {
  ConsentMessage({
    required this.analytics,
    required this.attribution,
    required this.ads,
  });

  bool analytics;

  bool attribution;

  bool ads;

  Object encode() {
    return <Object?>[
      analytics,
      attribution,
      ads,
    ];
  }

  static ConsentMessage decode(Object result) {
    result as List<Object?>;
    return ConsentMessage(
      analytics: result[0]! as bool,
      attribution: result[1]! as bool,
      ads: result[2]! as bool,
    );
  }
}

class AttributionMessage {
  AttributionMessage({
    this.source,
    this.campaign,
    this.network,
    this.clickId,
    required this.confidence,
    this.confidenceScore,
    this.raw,
  });

  String? source;

  String? campaign;

  String? network;

  String? clickId;

  String confidence;

  double? confidenceScore;

  Map<String?, String?>? raw;

  Object encode() {
    return <Object?>[
      source,
      campaign,
      network,
      clickId,
      confidence,
      confidenceScore,
      raw,
    ];
  }

  static AttributionMessage decode(Object result) {
    result as List<Object?>;
    return AttributionMessage(
      source: result[0] as String?,
      campaign: result[1] as String?,
      network: result[2] as String?,
      clickId: result[3] as String?,
      confidence: result[4]! as String,
      confidenceScore: result[5] as double?,
      raw: (result[6] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }
}

class DeepLinkMessage {
  DeepLinkMessage({
    this.path,
    this.params,
    this.url,
    required this.isDeferred,
  });

  String? path;

  Map<String?, String?>? params;

  String? url;

  bool isDeferred;

  Object encode() {
    return <Object?>[
      path,
      params,
      url,
      isDeferred,
    ];
  }

  static DeepLinkMessage decode(Object result) {
    result as List<Object?>;
    return DeepLinkMessage(
      path: result[0] as String?,
      params: (result[1] as Map<Object?, Object?>?)?.cast<String?, String?>(),
      url: result[2] as String?,
      isDeferred: result[3]! as bool,
    );
  }
}

class NativeAdMediaMessage {
  NativeAdMediaMessage({
    required this.type,
    required this.url,
  });

  String type;

  String url;

  Object encode() {
    return <Object?>[
      type,
      url,
    ];
  }

  static NativeAdMediaMessage decode(Object result) {
    result as List<Object?>;
    return NativeAdMediaMessage(
      type: result[0]! as String,
      url: result[1]! as String,
    );
  }
}

class NativeAdMessage {
  NativeAdMessage({
    required this.slotId,
    required this.adId,
    required this.format,
    this.headline,
    this.body,
    this.advertiser,
    this.cta,
    this.iconUrl,
    this.media,
    this.rating,
    required this.impressionUrls,
    required this.clickUrl,
    required this.viewablePixels,
    required this.viewableMs,
  });

  String slotId;

  String adId;

  String format;

  String? headline;

  String? body;

  String? advertiser;

  String? cta;

  String? iconUrl;

  NativeAdMediaMessage? media;

  double? rating;

  List<String?> impressionUrls;

  String clickUrl;

  double viewablePixels;

  int viewableMs;

  Object encode() {
    return <Object?>[
      slotId,
      adId,
      format,
      headline,
      body,
      advertiser,
      cta,
      iconUrl,
      media,
      rating,
      impressionUrls,
      clickUrl,
      viewablePixels,
      viewableMs,
    ];
  }

  static NativeAdMessage decode(Object result) {
    result as List<Object?>;
    return NativeAdMessage(
      slotId: result[0]! as String,
      adId: result[1]! as String,
      format: result[2]! as String,
      headline: result[3] as String?,
      body: result[4] as String?,
      advertiser: result[5] as String?,
      cta: result[6] as String?,
      iconUrl: result[7] as String?,
      media: result[8] as NativeAdMediaMessage?,
      rating: result[9] as double?,
      impressionUrls: (result[10] as List<Object?>?)!.cast<String?>(),
      clickUrl: result[11]! as String,
      viewablePixels: result[12]! as double,
      viewableMs: result[13]! as int,
    );
  }
}

class UpdateMessage {
  UpdateMessage({
    required this.available,
    required this.force,
    this.latestVersion,
    this.storeUrl,
    this.title,
    this.body,
  });

  bool available;

  bool force;

  String? latestVersion;

  String? storeUrl;

  String? title;

  String? body;

  Object encode() {
    return <Object?>[
      available,
      force,
      latestVersion,
      storeUrl,
      title,
      body,
    ];
  }

  static UpdateMessage decode(Object result) {
    result as List<Object?>;
    return UpdateMessage(
      available: result[0]! as bool,
      force: result[1]! as bool,
      latestVersion: result[2] as String?,
      storeUrl: result[3] as String?,
      title: result[4] as String?,
      body: result[5] as String?,
    );
  }
}

class AppMessageMessage {
  AppMessageMessage({
    required this.id,
    required this.type,
    required this.priority,
    this.title,
    this.body,
    this.ctaText,
    this.ctaUrl,
    this.imageUrl,
    required this.force,
    required this.minSessionSec,
    required this.frequency,
  });

  String id;

  String type;

  int priority;

  String? title;

  String? body;

  String? ctaText;

  String? ctaUrl;

  String? imageUrl;

  bool force;

  int minSessionSec;

  String frequency;

  Object encode() {
    return <Object?>[
      id,
      type,
      priority,
      title,
      body,
      ctaText,
      ctaUrl,
      imageUrl,
      force,
      minSessionSec,
      frequency,
    ];
  }

  static AppMessageMessage decode(Object result) {
    result as List<Object?>;
    return AppMessageMessage(
      id: result[0]! as String,
      type: result[1]! as String,
      priority: result[2]! as int,
      title: result[3] as String?,
      body: result[4] as String?,
      ctaText: result[5] as String?,
      ctaUrl: result[6] as String?,
      imageUrl: result[7] as String?,
      force: result[8]! as bool,
      minSessionSec: result[9]! as int,
      frequency: result[10]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ConfigMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else     if (value is ConsentMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else     if (value is AttributionMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else     if (value is DeepLinkMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else     if (value is NativeAdMediaMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else     if (value is NativeAdMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else     if (value is UpdateMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else     if (value is AppMessageMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return ConfigMessage.decode(readValue(buffer)!);
      case 130: 
        return ConsentMessage.decode(readValue(buffer)!);
      case 131: 
        return AttributionMessage.decode(readValue(buffer)!);
      case 132: 
        return DeepLinkMessage.decode(readValue(buffer)!);
      case 133: 
        return NativeAdMediaMessage.decode(readValue(buffer)!);
      case 134: 
        return NativeAdMessage.decode(readValue(buffer)!);
      case 135: 
        return UpdateMessage.decode(readValue(buffer)!);
      case 136: 
        return AppMessageMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class Ja0TrackerHostApi {
  /// Constructor for [Ja0TrackerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  Ja0TrackerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(ConfigMessage config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> requestTrackingConsent() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.requestTrackingConsent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> setConsent(ConsentMessage consent) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setConsent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[consent]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> trackEvent(String name, Map<String?, Object?> params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.trackEvent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<NativeAdMessage?> loadAd(String slotId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.loadAd$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[slotId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as NativeAdMessage?);
    }
  }

  Future<String?> getConfigJson(String key) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.getConfigJson$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  Future<void> setPushConsent(bool granted) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setPushConsent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[granted]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPushToken(String token) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setPushToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[token]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class Ja0TrackerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAttribution(AttributionMessage data);

  void onDeepLink(DeepLinkMessage data);

  void onUpdateAvailable(UpdateMessage data);

  void onMessage(AppMessageMessage data);

  static void setUp(Ja0TrackerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onAttribution$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onAttribution was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final AttributionMessage? arg_data = (args[0] as AttributionMessage?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onAttribution was null, expected non-null AttributionMessage.');
          try {
            api.onAttribution(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onDeepLink$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onDeepLink was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeepLinkMessage? arg_data = (args[0] as DeepLinkMessage?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onDeepLink was null, expected non-null DeepLinkMessage.');
          try {
            api.onDeepLink(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onUpdateAvailable$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onUpdateAvailable was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UpdateMessage? arg_data = (args[0] as UpdateMessage?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onUpdateAvailable was null, expected non-null UpdateMessage.');
          try {
            api.onUpdateAvailable(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final AppMessageMessage? arg_data = (args[0] as AppMessageMessage?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onMessage was null, expected non-null AppMessageMessage.');
          try {
            api.onMessage(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
