// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConfigMessage {
  var sdkKey: String
  var sdkSecret: String? = nil
  var appId: String? = nil
  var logLevel: String? = nil
  var waitForConsent: Bool? = nil
  var ingestBaseUrl: String? = nil
  var clickdBaseUrl: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfigMessage? {
    let sdkKey = pigeonVar_list[0] as! String
    let sdkSecret: String? = nilOrValue(pigeonVar_list[1])
    let appId: String? = nilOrValue(pigeonVar_list[2])
    let logLevel: String? = nilOrValue(pigeonVar_list[3])
    let waitForConsent: Bool? = nilOrValue(pigeonVar_list[4])
    let ingestBaseUrl: String? = nilOrValue(pigeonVar_list[5])
    let clickdBaseUrl: String? = nilOrValue(pigeonVar_list[6])

    return ConfigMessage(
      sdkKey: sdkKey,
      sdkSecret: sdkSecret,
      appId: appId,
      logLevel: logLevel,
      waitForConsent: waitForConsent,
      ingestBaseUrl: ingestBaseUrl,
      clickdBaseUrl: clickdBaseUrl
    )
  }
  func toList() -> [Any?] {
    return [
      sdkKey,
      sdkSecret,
      appId,
      logLevel,
      waitForConsent,
      ingestBaseUrl,
      clickdBaseUrl,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConsentMessage {
  var analytics: Bool
  var attribution: Bool
  var ads: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConsentMessage? {
    let analytics = pigeonVar_list[0] as! Bool
    let attribution = pigeonVar_list[1] as! Bool
    let ads = pigeonVar_list[2] as! Bool

    return ConsentMessage(
      analytics: analytics,
      attribution: attribution,
      ads: ads
    )
  }
  func toList() -> [Any?] {
    return [
      analytics,
      attribution,
      ads,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AttributionMessage {
  var source: String? = nil
  var campaign: String? = nil
  var network: String? = nil
  var clickId: String? = nil
  var confidence: String
  var confidenceScore: Double? = nil
  var raw: [String?: String?]? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttributionMessage? {
    let source: String? = nilOrValue(pigeonVar_list[0])
    let campaign: String? = nilOrValue(pigeonVar_list[1])
    let network: String? = nilOrValue(pigeonVar_list[2])
    let clickId: String? = nilOrValue(pigeonVar_list[3])
    let confidence = pigeonVar_list[4] as! String
    let confidenceScore: Double? = nilOrValue(pigeonVar_list[5])
    let raw: [String?: String?]? = nilOrValue(pigeonVar_list[6])

    return AttributionMessage(
      source: source,
      campaign: campaign,
      network: network,
      clickId: clickId,
      confidence: confidence,
      confidenceScore: confidenceScore,
      raw: raw
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      campaign,
      network,
      clickId,
      confidence,
      confidenceScore,
      raw,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeepLinkMessage {
  var path: String? = nil
  var params: [String?: String?]? = nil
  var url: String? = nil
  var isDeferred: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeepLinkMessage? {
    let path: String? = nilOrValue(pigeonVar_list[0])
    let params: [String?: String?]? = nilOrValue(pigeonVar_list[1])
    let url: String? = nilOrValue(pigeonVar_list[2])
    let isDeferred = pigeonVar_list[3] as! Bool

    return DeepLinkMessage(
      path: path,
      params: params,
      url: url,
      isDeferred: isDeferred
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      params,
      url,
      isDeferred,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdMediaMessage {
  var type: String
  var url: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdMediaMessage? {
    let type = pigeonVar_list[0] as! String
    let url = pigeonVar_list[1] as! String

    return NativeAdMediaMessage(
      type: type,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      url,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdMessage {
  var slotId: String
  var adId: String
  var format: String
  var headline: String? = nil
  var body: String? = nil
  var advertiser: String? = nil
  var cta: String? = nil
  var iconUrl: String? = nil
  var media: NativeAdMediaMessage? = nil
  var rating: Double? = nil
  var impressionUrls: [String?]
  var clickUrl: String
  var viewablePixels: Double
  var viewableMs: Int64



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdMessage? {
    let slotId = pigeonVar_list[0] as! String
    let adId = pigeonVar_list[1] as! String
    let format = pigeonVar_list[2] as! String
    let headline: String? = nilOrValue(pigeonVar_list[3])
    let body: String? = nilOrValue(pigeonVar_list[4])
    let advertiser: String? = nilOrValue(pigeonVar_list[5])
    let cta: String? = nilOrValue(pigeonVar_list[6])
    let iconUrl: String? = nilOrValue(pigeonVar_list[7])
    let media: NativeAdMediaMessage? = nilOrValue(pigeonVar_list[8])
    let rating: Double? = nilOrValue(pigeonVar_list[9])
    let impressionUrls = pigeonVar_list[10] as! [String?]
    let clickUrl = pigeonVar_list[11] as! String
    let viewablePixels = pigeonVar_list[12] as! Double
    let viewableMs = pigeonVar_list[13] is Int64 ? pigeonVar_list[13] as! Int64 : Int64(pigeonVar_list[13] as! Int32)

    return NativeAdMessage(
      slotId: slotId,
      adId: adId,
      format: format,
      headline: headline,
      body: body,
      advertiser: advertiser,
      cta: cta,
      iconUrl: iconUrl,
      media: media,
      rating: rating,
      impressionUrls: impressionUrls,
      clickUrl: clickUrl,
      viewablePixels: viewablePixels,
      viewableMs: viewableMs
    )
  }
  func toList() -> [Any?] {
    return [
      slotId,
      adId,
      format,
      headline,
      body,
      advertiser,
      cta,
      iconUrl,
      media,
      rating,
      impressionUrls,
      clickUrl,
      viewablePixels,
      viewableMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdateMessage {
  var available: Bool
  var force: Bool
  var latestVersion: String? = nil
  var storeUrl: String? = nil
  var title: String? = nil
  var body: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdateMessage? {
    let available = pigeonVar_list[0] as! Bool
    let force = pigeonVar_list[1] as! Bool
    let latestVersion: String? = nilOrValue(pigeonVar_list[2])
    let storeUrl: String? = nilOrValue(pigeonVar_list[3])
    let title: String? = nilOrValue(pigeonVar_list[4])
    let body: String? = nilOrValue(pigeonVar_list[5])

    return UpdateMessage(
      available: available,
      force: force,
      latestVersion: latestVersion,
      storeUrl: storeUrl,
      title: title,
      body: body
    )
  }
  func toList() -> [Any?] {
    return [
      available,
      force,
      latestVersion,
      storeUrl,
      title,
      body,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppMessageMessage {
  var id: String
  var type: String
  var priority: Int64
  var title: String? = nil
  var body: String? = nil
  var ctaText: String? = nil
  var ctaUrl: String? = nil
  var imageUrl: String? = nil
  var force: Bool
  var minSessionSec: Int64
  var frequency: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppMessageMessage? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! String
    let priority = pigeonVar_list[2] is Int64 ? pigeonVar_list[2] as! Int64 : Int64(pigeonVar_list[2] as! Int32)
    let title: String? = nilOrValue(pigeonVar_list[3])
    let body: String? = nilOrValue(pigeonVar_list[4])
    let ctaText: String? = nilOrValue(pigeonVar_list[5])
    let ctaUrl: String? = nilOrValue(pigeonVar_list[6])
    let imageUrl: String? = nilOrValue(pigeonVar_list[7])
    let force = pigeonVar_list[8] as! Bool
    let minSessionSec = pigeonVar_list[9] is Int64 ? pigeonVar_list[9] as! Int64 : Int64(pigeonVar_list[9] as! Int32)
    let frequency = pigeonVar_list[10] as! String

    return AppMessageMessage(
      id: id,
      type: type,
      priority: priority,
      title: title,
      body: body,
      ctaText: ctaText,
      ctaUrl: ctaUrl,
      imageUrl: imageUrl,
      force: force,
      minSessionSec: minSessionSec,
      frequency: frequency
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      priority,
      title,
      body,
      ctaText,
      ctaUrl,
      imageUrl,
      force,
      minSessionSec,
      frequency,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ConfigMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return ConsentMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return AttributionMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return DeepLinkMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeAdMediaMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeAdMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return UpdateMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return AppMessageMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConfigMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ConsentMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AttributionMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? DeepLinkMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdMediaMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? UpdateMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AppMessageMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Ja0TrackerHostApi {
  func initialize(config: ConfigMessage) throws
  func requestTrackingConsent(completion: @escaping (Result<String, Error>) -> Void)
  func setConsent(consent: ConsentMessage) throws
  func trackEvent(name: String, params: [String?: Any?]) throws
  func loadAd(slotId: String, completion: @escaping (Result<NativeAdMessage?, Error>) -> Void)
  func getConfigJson(key: String, completion: @escaping (Result<String?, Error>) -> Void)
  func setPushConsent(granted: Bool) throws
  func setPushToken(token: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class Ja0TrackerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `Ja0TrackerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Ja0TrackerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ConfigMessage
        do {
          try api.initialize(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let requestTrackingConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.requestTrackingConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestTrackingConsentChannel.setMessageHandler { _, reply in
        api.requestTrackingConsent { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestTrackingConsentChannel.setMessageHandler(nil)
    }
    let setConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let consentArg = args[0] as! ConsentMessage
        do {
          try api.setConsent(consent: consentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setConsentChannel.setMessageHandler(nil)
    }
    let trackEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.trackEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let paramsArg = args[1] as! [String?: Any?]
        do {
          try api.trackEvent(name: nameArg, params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackEventChannel.setMessageHandler(nil)
    }
    let loadAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.loadAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let slotIdArg = args[0] as! String
        api.loadAd(slotId: slotIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadAdChannel.setMessageHandler(nil)
    }
    let getConfigJsonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.getConfigJson\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConfigJsonChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.getConfigJson(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getConfigJsonChannel.setMessageHandler(nil)
    }
    let setPushConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setPushConsent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPushConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let grantedArg = args[0] as! Bool
        do {
          try api.setPushConsent(granted: grantedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPushConsentChannel.setMessageHandler(nil)
    }
    let setPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        do {
          try api.setPushToken(token: tokenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPushTokenChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol Ja0TrackerFlutterApiProtocol {
  func onAttribution(data dataArg: AttributionMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDeepLink(data dataArg: DeepLinkMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onUpdateAvailable(data dataArg: UpdateMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMessage(data dataArg: AppMessageMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class Ja0TrackerFlutterApi: Ja0TrackerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onAttribution(data dataArg: AttributionMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onAttribution\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDeepLink(data dataArg: DeepLinkMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onDeepLink\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onUpdateAvailable(data dataArg: UpdateMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onUpdateAvailable\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onMessage(data dataArg: AppMessageMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
