// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.ja0tracker.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfigMessage (
  val sdkKey: String,
  val sdkSecret: String? = null,
  val appId: String? = null,
  val logLevel: String? = null,
  val waitForConsent: Boolean? = null,
  val ingestBaseUrl: String? = null,
  val clickdBaseUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigMessage {
      val sdkKey = pigeonVar_list[0] as String
      val sdkSecret = pigeonVar_list[1] as String?
      val appId = pigeonVar_list[2] as String?
      val logLevel = pigeonVar_list[3] as String?
      val waitForConsent = pigeonVar_list[4] as Boolean?
      val ingestBaseUrl = pigeonVar_list[5] as String?
      val clickdBaseUrl = pigeonVar_list[6] as String?
      return ConfigMessage(sdkKey, sdkSecret, appId, logLevel, waitForConsent, ingestBaseUrl, clickdBaseUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sdkKey,
      sdkSecret,
      appId,
      logLevel,
      waitForConsent,
      ingestBaseUrl,
      clickdBaseUrl,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConsentMessage (
  val analytics: Boolean,
  val attribution: Boolean,
  val ads: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConsentMessage {
      val analytics = pigeonVar_list[0] as Boolean
      val attribution = pigeonVar_list[1] as Boolean
      val ads = pigeonVar_list[2] as Boolean
      return ConsentMessage(analytics, attribution, ads)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      analytics,
      attribution,
      ads,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AttributionMessage (
  val source: String? = null,
  val campaign: String? = null,
  val network: String? = null,
  val clickId: String? = null,
  val confidence: String,
  val confidenceScore: Double? = null,
  val raw: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttributionMessage {
      val source = pigeonVar_list[0] as String?
      val campaign = pigeonVar_list[1] as String?
      val network = pigeonVar_list[2] as String?
      val clickId = pigeonVar_list[3] as String?
      val confidence = pigeonVar_list[4] as String
      val confidenceScore = pigeonVar_list[5] as Double?
      val raw = pigeonVar_list[6] as Map<String?, String?>?
      return AttributionMessage(source, campaign, network, clickId, confidence, confidenceScore, raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      campaign,
      network,
      clickId,
      confidence,
      confidenceScore,
      raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeepLinkMessage (
  val path: String? = null,
  val params: Map<String?, String?>? = null,
  val url: String? = null,
  val isDeferred: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeepLinkMessage {
      val path = pigeonVar_list[0] as String?
      val params = pigeonVar_list[1] as Map<String?, String?>?
      val url = pigeonVar_list[2] as String?
      val isDeferred = pigeonVar_list[3] as Boolean
      return DeepLinkMessage(path, params, url, isDeferred)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      params,
      url,
      isDeferred,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAdMediaMessage (
  val type: String,
  val url: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdMediaMessage {
      val type = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      return NativeAdMediaMessage(type, url)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      url,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAdMessage (
  val slotId: String,
  val adId: String,
  val format: String,
  val headline: String? = null,
  val body: String? = null,
  val advertiser: String? = null,
  val cta: String? = null,
  val iconUrl: String? = null,
  val media: NativeAdMediaMessage? = null,
  val rating: Double? = null,
  val impressionUrls: List<String?>,
  val clickUrl: String,
  val viewablePixels: Double,
  val viewableMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdMessage {
      val slotId = pigeonVar_list[0] as String
      val adId = pigeonVar_list[1] as String
      val format = pigeonVar_list[2] as String
      val headline = pigeonVar_list[3] as String?
      val body = pigeonVar_list[4] as String?
      val advertiser = pigeonVar_list[5] as String?
      val cta = pigeonVar_list[6] as String?
      val iconUrl = pigeonVar_list[7] as String?
      val media = pigeonVar_list[8] as NativeAdMediaMessage?
      val rating = pigeonVar_list[9] as Double?
      val impressionUrls = pigeonVar_list[10] as List<String?>
      val clickUrl = pigeonVar_list[11] as String
      val viewablePixels = pigeonVar_list[12] as Double
      val viewableMs = pigeonVar_list[13].let { num -> if (num is Int) num.toLong() else num as Long }
      return NativeAdMessage(slotId, adId, format, headline, body, advertiser, cta, iconUrl, media, rating, impressionUrls, clickUrl, viewablePixels, viewableMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      slotId,
      adId,
      format,
      headline,
      body,
      advertiser,
      cta,
      iconUrl,
      media,
      rating,
      impressionUrls,
      clickUrl,
      viewablePixels,
      viewableMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdateMessage (
  val available: Boolean,
  val force: Boolean,
  val latestVersion: String? = null,
  val storeUrl: String? = null,
  val title: String? = null,
  val body: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdateMessage {
      val available = pigeonVar_list[0] as Boolean
      val force = pigeonVar_list[1] as Boolean
      val latestVersion = pigeonVar_list[2] as String?
      val storeUrl = pigeonVar_list[3] as String?
      val title = pigeonVar_list[4] as String?
      val body = pigeonVar_list[5] as String?
      return UpdateMessage(available, force, latestVersion, storeUrl, title, body)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      available,
      force,
      latestVersion,
      storeUrl,
      title,
      body,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AppMessageMessage (
  val id: String,
  val type: String,
  val priority: Long,
  val title: String? = null,
  val body: String? = null,
  val ctaText: String? = null,
  val ctaUrl: String? = null,
  val imageUrl: String? = null,
  val force: Boolean,
  val minSessionSec: Long,
  val frequency: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppMessageMessage {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val priority = pigeonVar_list[2].let { num -> if (num is Int) num.toLong() else num as Long }
      val title = pigeonVar_list[3] as String?
      val body = pigeonVar_list[4] as String?
      val ctaText = pigeonVar_list[5] as String?
      val ctaUrl = pigeonVar_list[6] as String?
      val imageUrl = pigeonVar_list[7] as String?
      val force = pigeonVar_list[8] as Boolean
      val minSessionSec = pigeonVar_list[9].let { num -> if (num is Int) num.toLong() else num as Long }
      val frequency = pigeonVar_list[10] as String
      return AppMessageMessage(id, type, priority, title, body, ctaText, ctaUrl, imageUrl, force, minSessionSec, frequency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      priority,
      title,
      body,
      ctaText,
      ctaUrl,
      imageUrl,
      force,
      minSessionSec,
      frequency,
    )
  }
}
private object MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConsentMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttributionMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeepLinkMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdMediaMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdateMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppMessageMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConfigMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ConsentMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AttributionMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DeepLinkMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeAdMediaMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeAdMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is UpdateMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is AppMessageMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface Ja0TrackerHostApi {
  fun initialize(config: ConfigMessage)
  fun requestTrackingConsent(callback: (Result<String>) -> Unit)
  fun setConsent(consent: ConsentMessage)
  fun trackEvent(name: String, params: Map<String?, Any?>)
  fun loadAd(slotId: String, callback: (Result<NativeAdMessage?>) -> Unit)
  fun getConfigJson(key: String, callback: (Result<String?>) -> Unit)
  fun setPushConsent(granted: Boolean)
  fun setPushToken(token: String)

  companion object {
    /** The codec used by Ja0TrackerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec
    }
    /** Sets up an instance of `Ja0TrackerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: Ja0TrackerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ConfigMessage
            val wrapped: List<Any?> = try {
              api.initialize(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.requestTrackingConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestTrackingConsent{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val consentArg = args[0] as ConsentMessage
            val wrapped: List<Any?> = try {
              api.setConsent(consentArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.trackEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val paramsArg = args[1] as Map<String?, Any?>
            val wrapped: List<Any?> = try {
              api.trackEvent(nameArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val slotIdArg = args[0] as String
            api.loadAd(slotIdArg) { result: Result<NativeAdMessage?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.getConfigJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            api.getConfigJson(keyArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setPushConsent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val grantedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setPushConsent(grantedArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ja0tracker.Ja0TrackerHostApi.setPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setPushToken(tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class Ja0TrackerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by Ja0TrackerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec
    }
  }
  fun onAttribution(dataArg: AttributionMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onAttribution$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDeepLink(dataArg: DeepLinkMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onDeepLink$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onUpdateAvailable(dataArg: UpdateMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onUpdateAvailable$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onMessage(dataArg: AppMessageMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.ja0tracker.Ja0TrackerFlutterApi.onMessage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
