// Autogenerated-style Pigeon output for mtracker (hand-written to match
// `dart run pigeon --input pigeons/messages.dart`, Pigeon ~21.x, Kotlin target).
//
// TODO(native): DO NOT edit by hand long-term. Regenerate with `dart run pigeon`.
// Matches the Dart `messages.g.dart` codec (type ids 129..134) and channel names.

package io.mtracker.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> = listOf(result)

private fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
        listOf(exception.code, exception.message, exception.details)
    } else {
        listOf(
            exception.javaClass.simpleName,
            exception.toString(),
            "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
        )
    }
}

/** Error class for passing custom error details to Flutter via a thrown PlatformException. */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null,
) : Throwable()

data class ConfigMessage(
    val sdkKey: String,
    val sdkSecret: String? = null,
    val appId: String? = null,
    val logLevel: String? = null,
    val waitForConsent: Boolean? = null,
    val ingestBaseUrl: String? = null,
    val clickdBaseUrl: String? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ConfigMessage {
            return ConfigMessage(
                sdkKey = pigeonVar_list[0] as String,
                sdkSecret = pigeonVar_list[1] as String?,
                appId = pigeonVar_list[2] as String?,
                logLevel = pigeonVar_list[3] as String?,
                waitForConsent = pigeonVar_list[4] as Boolean?,
                ingestBaseUrl = pigeonVar_list[5] as String?,
                clickdBaseUrl = pigeonVar_list[6] as String?,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(sdkKey, sdkSecret, appId, logLevel, waitForConsent, ingestBaseUrl, clickdBaseUrl)
}

data class ConsentMessage(
    val analytics: Boolean,
    val attribution: Boolean,
    val ads: Boolean,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ConsentMessage {
            return ConsentMessage(
                analytics = pigeonVar_list[0] as Boolean,
                attribution = pigeonVar_list[1] as Boolean,
                ads = pigeonVar_list[2] as Boolean,
            )
        }
    }

    fun toList(): List<Any?> = listOf(analytics, attribution, ads)
}

data class AttributionMessage(
    val source: String? = null,
    val campaign: String? = null,
    val network: String? = null,
    val clickId: String? = null,
    val confidence: String,
    val confidenceScore: Double? = null,
    val raw: Map<String?, String?>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): AttributionMessage {
            return AttributionMessage(
                source = pigeonVar_list[0] as String?,
                campaign = pigeonVar_list[1] as String?,
                network = pigeonVar_list[2] as String?,
                clickId = pigeonVar_list[3] as String?,
                confidence = pigeonVar_list[4] as String,
                confidenceScore = pigeonVar_list[5] as Double?,
                @Suppress("UNCHECKED_CAST")
                raw = pigeonVar_list[6] as Map<String?, String?>?,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(source, campaign, network, clickId, confidence, confidenceScore, raw)
}

data class DeepLinkMessage(
    val path: String? = null,
    val params: Map<String?, String?>? = null,
    val url: String? = null,
    val isDeferred: Boolean,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): DeepLinkMessage {
            return DeepLinkMessage(
                path = pigeonVar_list[0] as String?,
                @Suppress("UNCHECKED_CAST")
                params = pigeonVar_list[1] as Map<String?, String?>?,
                url = pigeonVar_list[2] as String?,
                isDeferred = pigeonVar_list[3] as Boolean,
            )
        }
    }

    fun toList(): List<Any?> = listOf(path, params, url, isDeferred)
}

data class NativeAdMediaMessage(
    val type: String,
    val url: String,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): NativeAdMediaMessage {
            return NativeAdMediaMessage(
                type = pigeonVar_list[0] as String,
                url = pigeonVar_list[1] as String,
            )
        }
    }

    fun toList(): List<Any?> = listOf(type, url)
}

data class NativeAdMessage(
    val slotId: String,
    val adId: String,
    val format: String,
    val headline: String? = null,
    val body: String? = null,
    val advertiser: String? = null,
    val cta: String? = null,
    val iconUrl: String? = null,
    val media: NativeAdMediaMessage? = null,
    val rating: Double? = null,
    val impressionUrls: List<String?>,
    val clickUrl: String,
    val viewablePixels: Double,
    val viewableMs: Long,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): NativeAdMessage {
            return NativeAdMessage(
                slotId = pigeonVar_list[0] as String,
                adId = pigeonVar_list[1] as String,
                format = pigeonVar_list[2] as String,
                headline = pigeonVar_list[3] as String?,
                body = pigeonVar_list[4] as String?,
                advertiser = pigeonVar_list[5] as String?,
                cta = pigeonVar_list[6] as String?,
                iconUrl = pigeonVar_list[7] as String?,
                media = pigeonVar_list[8] as NativeAdMediaMessage?,
                rating = pigeonVar_list[9] as Double?,
                @Suppress("UNCHECKED_CAST")
                impressionUrls = pigeonVar_list[10] as List<String?>,
                clickUrl = pigeonVar_list[11] as String,
                viewablePixels = pigeonVar_list[12] as Double,
                viewableMs = pigeonVar_list[13].let { if (it is Int) it.toLong() else it as Long },
            )
        }
    }

    fun toList(): List<Any?> = listOf(
        slotId, adId, format, headline, body, advertiser, cta, iconUrl,
        media, rating, impressionUrls, clickUrl, viewablePixels, viewableMs,
    )
}

data class UpdateMessage(
    val available: Boolean,
    val force: Boolean,
    val latestVersion: String? = null,
    val storeUrl: String? = null,
    val title: String? = null,
    val body: String? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): UpdateMessage {
            return UpdateMessage(
                available = pigeonVar_list[0] as Boolean,
                force = pigeonVar_list[1] as Boolean,
                latestVersion = pigeonVar_list[2] as String?,
                storeUrl = pigeonVar_list[3] as String?,
                title = pigeonVar_list[4] as String?,
                body = pigeonVar_list[5] as String?,
            )
        }
    }

    fun toList(): List<Any?> = listOf(available, force, latestVersion, storeUrl, title, body)
}

data class AppMessageMessage(
    val id: String,
    val type: String,
    val priority: Long,
    val title: String? = null,
    val body: String? = null,
    val ctaText: String? = null,
    val ctaUrl: String? = null,
    val imageUrl: String? = null,
    val force: Boolean,
    val minSessionSec: Long,
    val frequency: String,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): AppMessageMessage {
            return AppMessageMessage(
                id = pigeonVar_list[0] as String,
                type = pigeonVar_list[1] as String,
                priority = pigeonVar_list[2].let { if (it is Int) it.toLong() else it as Long },
                title = pigeonVar_list[3] as String?,
                body = pigeonVar_list[4] as String?,
                ctaText = pigeonVar_list[5] as String?,
                ctaUrl = pigeonVar_list[6] as String?,
                imageUrl = pigeonVar_list[7] as String?,
                force = pigeonVar_list[8] as Boolean,
                minSessionSec = pigeonVar_list[9].let { if (it is Int) it.toLong() else it as Long },
                frequency = pigeonVar_list[10] as String,
            )
        }
    }

    fun toList(): List<Any?> = listOf(
        id, type, priority, title, body, ctaText, ctaUrl, imageUrl, force, minSessionSec, frequency,
    )
}

private open class MessagesPigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
        return when (type) {
            129.toByte() -> (readValue(buffer) as? List<Any?>)?.let { ConfigMessage.fromList(it) }
            130.toByte() -> (readValue(buffer) as? List<Any?>)?.let { ConsentMessage.fromList(it) }
            131.toByte() -> (readValue(buffer) as? List<Any?>)?.let { AttributionMessage.fromList(it) }
            132.toByte() -> (readValue(buffer) as? List<Any?>)?.let { DeepLinkMessage.fromList(it) }
            133.toByte() -> (readValue(buffer) as? List<Any?>)?.let { NativeAdMediaMessage.fromList(it) }
            134.toByte() -> (readValue(buffer) as? List<Any?>)?.let { NativeAdMessage.fromList(it) }
            135.toByte() -> (readValue(buffer) as? List<Any?>)?.let { UpdateMessage.fromList(it) }
            136.toByte() -> (readValue(buffer) as? List<Any?>)?.let { AppMessageMessage.fromList(it) }
            else -> super.readValueOfType(type, buffer)
        }
    }

    override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
        when (value) {
            is ConfigMessage -> {
                stream.write(129)
                writeValue(stream, value.toList())
            }
            is ConsentMessage -> {
                stream.write(130)
                writeValue(stream, value.toList())
            }
            is AttributionMessage -> {
                stream.write(131)
                writeValue(stream, value.toList())
            }
            is DeepLinkMessage -> {
                stream.write(132)
                writeValue(stream, value.toList())
            }
            is NativeAdMediaMessage -> {
                stream.write(133)
                writeValue(stream, value.toList())
            }
            is NativeAdMessage -> {
                stream.write(134)
                writeValue(stream, value.toList())
            }
            is UpdateMessage -> {
                stream.write(135)
                writeValue(stream, value.toList())
            }
            is AppMessageMessage -> {
                stream.write(136)
                writeValue(stream, value.toList())
            }
            else -> super.writeValue(stream, value)
        }
    }
}

/** Host API: Dart -> native. Implemented by the plugin. */
interface MtrackerHostApi {
    fun initialize(config: ConfigMessage)
    fun requestTrackingConsent(callback: (Result<String>) -> Unit)
    fun setConsent(consent: ConsentMessage)
    fun trackEvent(name: String, params: Map<String?, Any?>)
    fun loadAd(slotId: String, callback: (Result<NativeAdMessage?>) -> Unit)
    fun getConfigJson(key: String, callback: (Result<String?>) -> Unit)
    fun setPushConsent(granted: Boolean)
    fun setPushToken(token: String)

    companion object {
        /** The codec used by MtrackerHostApi. */
        val codec: MessageCodec<Any?> by lazy { MessagesPigeonCodec() }

        /** Sets up an instance of `MtrackerHostApi` to handle messages through `binaryMessenger`. */
        fun setUp(
            binaryMessenger: BinaryMessenger,
            api: MtrackerHostApi?,
            messageChannelSuffix: String = "",
        ) {
            val separatedMessageChannelSuffix =
                if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.initialize$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val configArg = args[0] as ConfigMessage
                        val wrapped: List<Any?> = try {
                            api.initialize(configArg)
                            listOf(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.requestTrackingConsent$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        api.requestTrackingConsent { result: Result<String> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                reply.reply(wrapResult(result.getOrNull()))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.setConsent$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val consentArg = args[0] as ConsentMessage
                        val wrapped: List<Any?> = try {
                            api.setConsent(consentArg)
                            listOf(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.trackEvent$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val nameArg = args[0] as String
                        @Suppress("UNCHECKED_CAST")
                        val paramsArg = args[1] as Map<String?, Any?>
                        val wrapped: List<Any?> = try {
                            api.trackEvent(nameArg, paramsArg)
                            listOf(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.loadAd$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val slotIdArg = args[0] as String
                        api.loadAd(slotIdArg) { result: Result<NativeAdMessage?> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                reply.reply(wrapResult(result.getOrNull()))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.getConfigJson$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val keyArg = args[0] as String
                        api.getConfigJson(keyArg) { result: Result<String?> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                reply.reply(wrapResult(result.getOrNull()))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.setPushConsent$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val grantedArg = args[0] as Boolean
                        val wrapped: List<Any?> = try {
                            api.setPushConsent(grantedArg)
                            listOf(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel = BasicMessageChannel<Any?>(
                    binaryMessenger,
                    "dev.flutter.pigeon.mtracker.MtrackerHostApi.setPushToken$separatedMessageChannelSuffix",
                    codec,
                )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val tokenArg = args[0] as String
                        val wrapped: List<Any?> = try {
                            api.setPushToken(tokenArg)
                            listOf(null)
                        } catch (exception: Throwable) {
                            wrapError(exception)
                        }
                        reply.reply(wrapped)
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}

/** Flutter API: native -> Dart callbacks. Called by the plugin. */
class MtrackerFlutterApi(
    private val binaryMessenger: BinaryMessenger,
    private val messageChannelSuffix: String = "",
) {
    companion object {
        /** The codec used by MtrackerFlutterApi. */
        val codec: MessageCodec<Any?> by lazy { MessagesPigeonCodec() }
    }

    private val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""

    fun onAttribution(dataArg: AttributionMessage, callback: (Result<Unit>) -> Unit) {
        val channelName =
            "dev.flutter.pigeon.mtracker.MtrackerFlutterApi.onAttribution$separatedMessageChannelSuffix"
        val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
        channel.send(listOf(dataArg)) {
            callback(Result.success(Unit))
        }
    }

    fun onDeepLink(dataArg: DeepLinkMessage, callback: (Result<Unit>) -> Unit) {
        val channelName =
            "dev.flutter.pigeon.mtracker.MtrackerFlutterApi.onDeepLink$separatedMessageChannelSuffix"
        val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
        channel.send(listOf(dataArg)) {
            callback(Result.success(Unit))
        }
    }

    fun onUpdateAvailable(dataArg: UpdateMessage, callback: (Result<Unit>) -> Unit) {
        val channelName =
            "dev.flutter.pigeon.mtracker.MtrackerFlutterApi.onUpdateAvailable$separatedMessageChannelSuffix"
        val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
        channel.send(listOf(dataArg)) {
            callback(Result.success(Unit))
        }
    }

    fun onMessage(dataArg: AppMessageMessage, callback: (Result<Unit>) -> Unit) {
        val channelName =
            "dev.flutter.pigeon.mtracker.MtrackerFlutterApi.onMessage$separatedMessageChannelSuffix"
        val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
        channel.send(listOf(dataArg)) {
            callback(Result.success(Unit))
        }
    }
}
